### ISSUE TITLE
Use existing Websphere MQ 6

### ISSUE THREAD

**Issue by blommish** [magnuspalmer/wmbtesting#1]
Hi,

I'm going to implement testing for an WMQ 6 and this looks really awesome. However I'm a bit confused of how to get it to work with WMQ 6. So we do not got the broker but only the MQ.
We got an instance of websphere running and I will use my code against that instance

What is MQ_JAVA_INSTALL_PATH? 
Is there something else thats needs to be setup? Since your application uses the broker, will it work with only the MQ ?

**Comment by magnuspalmer** [comment]
Hi, sorry for a late answer.

It should work with WMQ 6 as well.
The MQ_JAVA_INSTALL_PATH is a path set when installing WMQ7 (don't remember if it does this on WMQ6). Typically C:\Program Files (x86)\IBM\WebSphere MQ\java on Windows.
You could set this yourself to what ever you like. An alternative is to publish the WMQ jar-files you need to a Maven repo like Artifactory or Nexus and add a dependency like you normally do.

As you spotted this has actually no relationship with the IBM broker itself, only WMQ, so if you use Biztalk or something else in the middle it doesn't matter.
